### ISSUE TITLE
client side error

### ISSUE THREAD

**Issue by princejoogie** [joshxfi/trackAsOne#18]
not sure of the cause but i logged in, pressed `home` tab then this error appeared. it was gone when i reloaded.

make sure to handle firebase query errors properly 

![image](https://user-images.githubusercontent.com/47204120/151938249-c8c752a8-b583-4736-9414-f56a61d9aa35.png)

**Comment by joshxfi** [comment]
I tried to reproduce this with a new account but didn't get this error. I'll try to check what caused that error. Also, logging in should redirect you to `/home`
