### ISSUE TITLE
page layout (enhancement)

### ISSUE THREAD

**Issue by princejoogie** [joshxfi/trackAsOne#19]
i noticed that when switching between pages, you have this quick fade animation which makes it feel "laggy" somehow. try only adding those animations to the content not the navbar layout.

also another enhancement is to apply NextJS's [Layout](https://nextjs.org/docs/basic-features/layouts) for pages. this will slightly improve perfomance as it uses react's concept of [Reconciliation](https://reactjs.org/docs/reconciliation.html)

![tao](https://user-images.githubusercontent.com/47204120/151939072-a4bfd454-c816-4b8c-bb49-c0c9e9c3977a.gif)

**Comment by joshxfi** [comment]
nice! I'll implement next's layout. & I guess I'll just remove `framer-motion` for performance since I barely use it on other components
