### ISSUE TITLE
sort tasks radio button not aligned properly

### ISSUE THREAD

**Issue by hyamero** [joshxfi/trackAsOne#62]
Browser used: **Edge** 

![image](https://user-images.githubusercontent.com/78056869/162574704-4d9fe537-6470-4df2-be26-130701c85898.png)

**Comment by tomasmilkintas** [comment]
Hey - decided to jump in on the open-source contributions to help out :) so this does happen to be my first issue!

**Comment by joshxfi** [comment]
Thanks @tomasmilkintas !
